[package]
name = "rise_of_the_frogs"
version = "0.1.12"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.8"
strum = "0.24.1"
strum_macros = "0.24.3"
rand = "0.8.4"

[dev-dependencies]
rstest = "0.16.0"